# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 14:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('downloader', models.PositiveSmallIntegerField(choices=[(0, 'youtube-dl')], null=True)),
                ('celery_id', models.UUIDField(null=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Queued'), (1, 'Downloading'), (2, 'Processing'), (3, 'Finished'), (4, 'Error'), (5, 'Canceled')], default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('release', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rls.Release')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TaskTraceback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('download_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracebacks', to='rlsget.DownloadTask')),
            ],
        ),
    ]
