# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
